### ISSUE TITLE
Benchmarking 

### ISSUE THREAD

**Issue by jwoertink** [SushiChain/crystal-base32#1]
I'm not very good at it, but I'd like to get better, so I decided to put this version up against [this one](https://github.com/noumar/base32). I just wanted to report what I came across in case it helps.

Now since both version use the same constant, I went to the `lib/crystal-base32` folder and renamed the constant from `Base32` => `SBase32`. No other changes were made. Both are using master branch. The sample is ran using `crystal build --release test.cr` and `./test`

```crystal
require "base32"
require "crystal-base32"
require "benchmark"

Benchmark.bm do |x|
  x.report("base32:") do
    100_000.times do |i|
      Base32.encode("chunky bacon! #{i}")
    end
  end

  x.report("crystal-base32:") do
    100_000.times do |i|
      SBase32.encode("chunky bacon! #{i}")
    end
  end
end
```

```
[13:20PM] sandbox$ ./test
                      user     system      total        real
base32:           0.100000   0.100000   0.200000 (  0.126664)
crystal-base32:   1.570000   1.270000   2.840000 (  1.830132)
```

```text
Crystal 0.24.2 (2018-03-10)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

**Comment by kingsleyh** [comment]
Ah awesome thanks - I didn’t realise the other base32 existed or I would not have written mine lol ! Also the other one seems a lot faster!

**Comment by kingsleyh** [comment]
closing this now - as I've made some perf improvements

```
                      user     system      total        real
crystal-base32:   0.150000   0.410000   0.560000 (  0.260205)
```
